const ADD_SEATS = 'ADD_SEATS'
const ADD_DEFAULT_SEATS = 'ADD_DEFAULT_SEATS'
const REMOVE_DEFAULT_SEATS = 'REMOVE_DEFAULT_SEATS'

export default {
    ADD_SEATS,
    ADD_DEFAULT_SEATS,
    REMOVE_DEFAULT_SEATS
}